name = "agentconnect"
compatibility_date = "2024-07-04"
workers_dev = false
preview_urls = false
send_metrics = false
placement = { mode = "smart" }

main = "worker.mjs"

[assets]
directory = "./dist"
binding = "ASSETS"

[env.staging]
name = "agentconnect-staging" 

routes = [
  { pattern = "agentconnect.staging.polygon.technology/*", custom_domain = true }  
]

[env.production]
name = "agentconnect-production" 

routes = [
  { pattern = "agentconnect.polygon.technology/*", custom_domain = true }  
]
